### ISSUE TITLE
OSError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by 571946808** [deNsuh/segan-pytorch#19]
hello,how to resolve this problem,thank you.
Traceback (most recent call last):
  File "model.py", line 399, in <module>
    for i, sample_batch_pairs in enumerate(random_data_loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 623, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
OSError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/content/drive/SEGAN/data_generator.py", line 56, in __getitem__
    pair = np.load(self.filepaths[idx])
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py", line 404, in load
    magic = fid.read(N)
OSError: [Errno 5] Input/output error

**Comment by dansuh17** [comment]
Do you have the appropriate files in the target directory that have been preprocessed and properly [`np.save()`](https://github.com/deNsuh/segan-pytorch/blob/master/data_preprocess.py#L126) ed?

**Comment by 571946808** [comment]
yes，it interrupt at "Epoch 1	Step 90", the files is in the target directory

**Comment by dansuh17** [comment]
Hmm, the `Input/output error` is not that common and the error itself does not actually tell much. In my experience, those are mostly seen when there is a problem with our OS / hardware. It might be your SSD / RAM being broken, insufficient memory, or your disk (in which you store the training files) are broken.

**Comment by BoostMom** [comment]
have you solved the problem?
